### ISSUE TITLE
Particles not rotating in Safari

### ISSUE THREAD

**Issue by roydigerhund** [herrethan/react-confetti-explosion#1]
For me, the particles are not rotating in Safari. In Chrome and Firefox everything looks good. 

I don't know yet why this does not work, Safari should support the `rotate3d` property.

**Comment by roydigerhund** [comment]
I created a pull request with a fix https://github.com/herrethan/react-confetti-explosion/pull/2

And you could improve the `.prettierrc.json`, your code base contains trailing commas but the setting is missing in the config. When I run prettier it will remove all trailing commas.

**Comment by herrethan** [comment]
Thanks @roydigerhund! Changes incorporated in [latest changes](https://github.com/herrethan/react-confetti-explosion/commit/01a01888cf4f59bd1d195b8da4383a9557de5ed2).
