### ISSUE TITLE
Works for web but not ios?

### ISSUE THREAD

**Issue by AnonymousAmalgrams** [herrethan/react-confetti-explosion#10]
I came across your package in the npm listings, not sure if it's intended to work on ios but if this could be supported without much trouble that would be very helpful for me. As it stands when calling ConfettiExplosion the following error is received: "View config getter callback for component 'div' must be a function (received 'undefined'). Make sure to start component names with a capital letter."

**Comment by herrethan** [comment]
hey @AnonymousAmalgrams, this is a React-based project (not React Native for example), so is intended for web. It has been tested on iOS safari and works as expected, but beyond that I'm not sure how much it would require to port over to some native framework.
