### ISSUE TITLE
How do I check if the confetti has ended? 

### ISSUE THREAD

**Issue by bhatvikrant** [herrethan/react-confetti-explosion#12]
A onConfettiComplete prop would help I guess

**Comment by herrethan** [comment]
I like this idea @bhatvikrant, will implement!

**Comment by dephraiim** [comment]
Any progress?

**Comment by ephraimduncan** [comment]
Any progress on this?

**Comment by stephenasuncionDEV** [comment]
Waiting on this till I switch to this library.

**Comment by ephraimduncan** [comment]
@stephenasuncionDEV What other alternatives are you using?

**Comment by herrethan** [comment]
Updated, onComplete is added! https://github.com/herrethan/react-confetti-explosion/commit/ccc5bf69de8d88055e89bd448d490d4e06b25c3c

**Comment by shivavelingker** [comment]
this doesn't seem to be working anymore: https://codesandbox.io/p/sandbox/confetti-explosion-vslnjg
