### ISSUE TITLE
Not working above other components.

### ISSUE THREAD

**Issue by Hariiikrishnan** [herrethan/react-confetti-explosion#13]
Works on Component with No Elements as said in example. But not working above the elements, even after changed z-index.

**Comment by Hariiikrishnan** [comment]
I'm the one who did mistake.

**Comment by razvanilin** [comment]
Did you solve this issue? I'm trying to use this on a Modal with a high `z-index`, but couldn't find a way to pass a higher `z-index` to the confetti div

**Comment by Hariiikrishnan** [comment]
> Did you solve this issue? I'm trying to use this on a Modal with a high `z-index`, but couldn't find a way to pass a higher `z-index` to the confetti div

I removed the  z index values which I gave to the other elements.
