### ISSUE TITLE
The position is happening only on the left top corner. How to set it in the middle of the screen?

### ISSUE THREAD

**Issue by DercilioFontes** [herrethan/react-confetti-explosion#20]
I wonder if that is an issue or if I must do something. But the element is positioned at the left top corner, and I couldn't change that.

![Screenshot 2023-10-16 at 10 46 44 AM](https://github.com/herrethan/react-confetti-explosion/assets/20172847/5ea31c5e-0643-479d-9b0f-a1f0f9ecbe5f)
![Screenshot 2023-10-16 at 10 48 31 AM](https://github.com/herrethan/react-confetti-explosion/assets/20172847/d6439894-f8b3-4627-aa39-00906307e455)

**Comment by lub0v** [comment]
Hey @DercilioFontes, try to place it inside the container that is positioned the way you want. 

```
<div style={{ position: 'absolute', top: '50%', left: '50%' }}>
<ConfettiExplosion/>
</div>
```

**Comment by DercilioFontes** [comment]
Hi @lub0v,

It worked. 

I also needed to move the component to be a child of my `IonPage` component. It was in inside components with if/else conditions.

```typescript
    <IonPage className="hiddenScrollbar">
      {showAnimation ? (
        <div style={{ position: 'absolute', top: '50%', left: '50%' }}>
          <ConfettiExplosion
            colors={['#284A5A', '#2D8278', '#476482', '#479B5A']}
            width={1400}
            force={0.6}
            particleCount={200}
          />
        </div>
      ) : null}
```
Thank you.
