### ISSUE TITLE
sheetManager is undefined

### ISSUE THREAD

**Issue by lakardion** [herrethan/react-confetti-explosion#5]
Hey there thanks for publishing this package!

I'm having an issue using it and I don't know exactly what it might be (probably the postcss processor that I am using?) I tried both locally (vite) and in a code sandbox and I'm getting the same error in both places

This is the codesandbox, which I copied over your example from the repo to reproduce the error : https://codesandbox.io/s/vigorous-shadow-n17mnx?file=/src/index.tsx

**Comment by MarcBuch** [comment]
Hi, I get the same error with Typescript.

**Comment by adamwdennis** [comment]
I am also getting this error with Typescript, (Tailwind/PostCSS/Autoprefixer), NextJS

edit: looks like it's related to `@mui/styles`:

from the [mui website](https://mui.com/system/styles/basics/):
`@mui/styles is not compatible with [React.StrictMode](https://reactjs.org/docs/strict-mode.html) or React 18.`

**Comment by jt6677** [comment]
same error here.  You cannot use strictmode with this. I managed to get it to 'explode' but some funky stuff happened also. moving on

**Comment by herrethan** [comment]
Hey folks, thanks for the feedback. I finally had a moment to refresh this to React 18 and remove the `@mui/styles` dependency in favor of `react-jss`, so these issues should be resolved with the [latest v2.x changes](https://github.com/herrethan/react-confetti-explosion#updates-in-v2x).
