### ISSUE TITLE
makeStyles.js:156 Uncaught TypeError: Cannot read properties of undefined (reading 'refs')

### ISSUE THREAD

**Issue by estoylive** [herrethan/react-confetti-explosion#6]
not sure what's going on here

**Comment by joshbedo** [comment]
having the same issue

**Comment by DercilioFontes** [comment]
I see that it happens with `<React.StrictMode>`. I'm trying to see if there is a workaround to avoid the error.

**Comment by DercilioFontes** [comment]
It depends on a deprecated library.
```
"dependencies": {
    "@material-ui/styles": "^4.11.5",
    "lodash": "^4.17.21"
  },
```
![Screenshot 2022-11-29 at 3 20 07 PM](https://user-images.githubusercontent.com/20172847/204639394-d240ad54-8b4b-4ea5-a31f-4e3d2535f07b.png)

**Comment by markmaci** [comment]
I was able to circumvent this by turning off strict mode. Not sure how sound of a solution this is but it works for now.

**Comment by DercilioFontes** [comment]
> It depends on a deprecated library.
> 
> ```
> "dependencies": {
>     "@material-ui/styles": "^4.11.5",
>     "lodash": "^4.17.21"
>   },
> ```
> 
> ![Screenshot 2022-11-29 at 3 20 07 PM](https://user-images.githubusercontent.com/20172847/204639394-d240ad54-8b4b-4ea5-a31f-4e3d2535f07b.png)

I sent a PR to update the libraries (https://github.com/herrethan/react-confetti-explosion/pull/7)

**Comment by DercilioFontes** [comment]
I didn't get any feedback about the PR sent. So, I created a forked package with the updates, https://www.npmjs.com/package/confetti-explosion-react.

**Comment by herrethan** [comment]
Thanks all! Closing this as we're now using `react-jss` for styles. The latest changes [here](https://github.com/herrethan/react-confetti-explosion#updates-in-v2x).
