### ISSUE TITLE
Deprecation warning for @material-ui/styles

### ISSUE THREAD

**Issue by tphalp** [herrethan/react-confetti-explosion#8]
FYI:
```
npm WARN deprecated @material-ui/styles@4.11.5: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
```

**Comment by herrethan** [comment]
Thanks @tphalp, finally updated to use [react-jss](https://github.com/herrethan/react-confetti-explosion/blob/master/src/confetti/styles.ts#L1). Latest updates [documented here](https://github.com/herrethan/react-confetti-explosion#updates-in-v2x).
