### ISSUE TITLE
Exports a IConfetti type

### ISSUE THREAD

**Issue by JoaoVictor6** [herrethan/react-confetti-explosion#9]
Maybe is very interesting to can use the isolate objects config of JSX and still with ts types  :)

**Comment by herrethan** [comment]
Hey thanks @JoaoVictor6, this was on my list of todos ~ now `ConfettiProps` interface is exported, which extends React div props, see [latest updates](https://github.com/herrethan/react-confetti-explosion#updates-in-v2x).
